<!--
document.writeln(" <div class=\"efusion-wrapcen\"> ");
document.writeln(" <div id=\"efusion-header\"> ");
document.writeln("      ");
document.writeln(" <div id=\"efusion-logo\"><a href=\"http://stores.ebay.com/The-Whole-Shebang-New-York\"><img src=\"http://i61.photobucket.com/albums/h76/Nimo18/new%20one1_zpsmhcqgpik.png\" width=\"180\" height=\"90\" /></a></div> ");
document.writeln("  ");
document.writeln("  ");
document.writeln(" <!--STORE SEARCH //STARTS--> ");
document.writeln(" <div id=\"efusion-search\"> ");
document.writeln("           <form action=\"/The-Whole-Shebang-New-York/_i.html\" style=\"display: inline;\" method=\"get\" name=\"Search\"> ");
document.writeln("             <div id=\"efusion-input\"> ");
document.writeln("               <input name=\"_nkw\" type=\"text\" class=\"v4sbox\" onclick=\"this.value='';\" value=\"Store Search\" size=\"13\" maxlength=\"300\" /> ");
document.writeln("             </div> ");
document.writeln("             <div id=\"efusion-submit\"> ");
document.writeln("               <input name=\"submit\" type=\"submit\"  class=\"btn-search\" /> ");
document.writeln("             </div> ");
document.writeln("           </form> ");
document.writeln(" </div> ");
document.writeln(" <!--STORE SEARCH //ENDS--> ");
document.writeln("  ");
document.writeln(" <!--STORE PAGES NAVIGATION //STARTS--> ");
document.writeln(" <div id=\"efusion-nav\"> ");
document.writeln(" 	<ul> ");
document.writeln("     	<li><a href=\"\">Contact Us</a></li> ");
document.writeln("         <li><a href=\"\">Ending Soon</a></li> ");
document.writeln("         <li><a href=\"\">New Arrivals</a></li> ");
document.writeln("         <li><a href=\"\">Add to Favorites</a></li> ");
document.writeln("         <li><a href=\"\">Home</a></li> ");
document.writeln("     </ul> ");
document.writeln(" </div> ");
document.writeln(" <!--STORE PAGES NAVIGATION //END--> ");
document.writeln("  ");
document.writeln(" <!--STORE NAVIGATION //STARTS--> ");
document.writeln(" <div id=\"efusion-menu\"> ");
document.writeln("   <div id=\"efusion-menu-holder\"> ");
document.writeln("     <ul id=\"efusionmenu\"> ");
document.writeln("     	<li><a href=\"\">MEN</a></li>  ");
document.writeln("         <li><a href=\"\">MISSY</a></li>  ");
document.writeln("         <li><a href=\"\">JUNIOR</a></li>  ");
document.writeln("         <li><a href=\"\">GIRLS</a></li> ");
document.writeln("         <li><a href=\"\">BOYS</a></li>  ");
document.writeln("         <li><a href=\"\">PLUS SIZE</a></li>  ");
document.writeln("         <li class=\"showall\"><a href=\"\">SHOW ALL</a></li> ");
document.writeln("     </ul> ");
document.writeln("   </div> ");
document.writeln(" </div> ");
document.writeln(" <!--STORE NAVIGATION //ENDS--> ");
document.writeln(" </div> ");
document.writeln("  ");
document.writeln(" <!--STORE BANNER //STARTS--> ");
document.writeln(" <div id=\"banner-holder\"> ");
document.writeln("<img src=\"http://i61.photobucket.com/albums/h76/Nimo18/TheWholeShebang_zpsmuzcczlp.jpg?t=1472515651\" width=\"994px\" height=\"\" />  ");
document.writeln(" 	 ");
document.writeln(" </div> ");
document.writeln(" <!--STORE BANNER //ENDS--> ");
document.writeln(" </div> ");
document.writeln("  ");
 // -->
